import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";

const geistSans = localFont({
  src: "./fonts/NotoSansKR-Regular.ttf",
  variable: "--font-geist-sans",
  weight: "400 600",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
