import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

// Redux
import Providers from "@/components/Providers";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-noto-sans-kr",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${notoSansKr.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <Header />
          <div className="pt-[57px]">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
